package me.manhunt.gui.enums;

public enum GuiItemType {
    PAGINATION_FIRST_PAGE,
    PAGINATION_LAST_PAGE,
    PAGINATION_NEXT_PAGE,
    PAGINATION_PREVIOUS_PAGE,
    PAGINATION_CURRENT_PAGE,
    CREATE_MANHUNT_ITEM,
    CREATE_ADD_SPEEDRUNNER_ITEM,
    CREATE_ADD_HUNTER_ITEM
}
