package me.manhunt.gui.enums;

public enum GuiItemType {
    PAGINATION_FIRST_PAGE,
    PAGINATION_LAST_PAGE,
    PAGINATION_NEXT_PAGE,
    PAGINATION_PREVIOUS_PAGE,
    PAGINATION_CURRENT_PAGE,
    CREATE_MANHUNT_ITEM,
    CREATE_ADD_SPEEDRUNNER_ITEM,
    CREATE_ADD_HUNTER_ITEM,
    MAIN_ROSTER_ITEM,
    MAIN_WORLD_ITEM,
    MAIN_GAME_ITEM,
    MAIN_GOAL_ITEM,
    MAIN_SPEEDRUNNER_ITEM,
    MAIN_HUNTER_ITEM,
    MAIN_DISBAND_ITEM,
    WORLD_WORLD_TYPE_ITEM,
    WORLD_GENERATE_STRUCTURES_ITEM,
    WORLD_SEED_ITEM,
    WORLD_DIFFICULTY_ITEM,
    WORLD_GAME_RULE_ITEM
}
